version: '3'
services:
  ordertransaction:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres13
    environment:
      DB_HOST: postgres13
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres123
      DB_NAME: order_transaction_db
    ports:
      - "8080:8080"
      
  postgres13:
    image: postgres:13
    environment:
      POSTGRES_DB: order_transaction_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "6000:6000"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
